// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLcBEg8ZD2bvi_BB7UA7v9u46oZiXsHf0',
    appId: '1:368070425344:web:72cad3c172aa6690f6d1e5',
    messagingSenderId: '368070425344',
    projectId: 'schoolconnect-88153',
    authDomain: 'schoolconnect-88153.firebaseapp.com',
    storageBucket: 'schoolconnect-88153.firebasestorage.app',
    measurementId: 'G-Q80ZS8DD1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3F5COL2h0zjwaH6UcEQ1-IINs5teCsWw',
    appId: '1:368070425344:android:19bcd4ee8be57b49f6d1e5',
    messagingSenderId: '368070425344',
    projectId: 'schoolconnect-88153',
    storageBucket: 'schoolconnect-88153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCar8d1NfMyY82BprKbnv6Bhxdxa8bW8zU',
    appId: '1:368070425344:ios:9f31fa8c6f5f8d7df6d1e5',
    messagingSenderId: '368070425344',
    projectId: 'schoolconnect-88153',
    storageBucket: 'schoolconnect-88153.firebasestorage.app',
    iosBundleId: 'com.example.schoolConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCar8d1NfMyY82BprKbnv6Bhxdxa8bW8zU',
    appId: '1:368070425344:ios:9f31fa8c6f5f8d7df6d1e5',
    messagingSenderId: '368070425344',
    projectId: 'schoolconnect-88153',
    storageBucket: 'schoolconnect-88153.firebasestorage.app',
    iosBundleId: 'com.example.schoolConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLcBEg8ZD2bvi_BB7UA7v9u46oZiXsHf0',
    appId: '1:368070425344:web:ae22c0ddf8451804f6d1e5',
    messagingSenderId: '368070425344',
    projectId: 'schoolconnect-88153',
    authDomain: 'schoolconnect-88153.firebaseapp.com',
    storageBucket: 'schoolconnect-88153.firebasestorage.app',
    measurementId: 'G-4L5SV1ZZ1D',
  );

}